version: '3.8'
name: enjoit-back_end
services:
  postgres:
    image: postgres:16.1
    container_name: enjoit-postgres
    ports:
      - '5432:5432'
    volumes:
      - './docker_data/pg_data:/var/lib/postgresql/data'
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:8.2
    container_name: enjoit-pgadmin
    depends_on:
      - postgres
    ports:
      - '8080:80'
    volumes:
      - './docker_data/pgadmin_data:/var/lib/pgadmin'
    env_file:
      - .env
